<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Authorizationss\**" />
    <EmbeddedResource Remove="Authorizationss\**" />
    <None Remove="Authorizationss\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\DomainPlayground.SharedKernel\DomainPlayground.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Users\" />
  </ItemGroup>

</Project>
