// <auto-generated />
using System;
using DomainPlayground.Infrastructure.Persistence.Commands.Common.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DomainPlayground.Infrastructure.Persistence.Commands.Migrations
{
    [DbContext(typeof(ApplicationCommandDbContext))]
    partial class ApplicationCommandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainPlayground.Core.Domain.Authorization.Permissions.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("DomainPlayground.Core.Domain.Authorization.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("DomainPlayground.Core.Domain.Authorization.UserAccesses.UserAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserAccesses", (string)null);
                });

            modelBuilder.Entity("DomainPlayground.Core.Domain.Authorization.Roles.Role", b =>
                {
                    b.OwnsMany("DomainPlayground.Core.Domain.Authorization.Roles.ValueObjects.RolePermission", "Permissions", b1 =>
                        {
                            b1.Property<int>("RoleId")
                                .HasColumnType("int");

                            b1.Property<int>("PermissionId")
                                .HasColumnType("int");

                            b1.HasKey("RoleId", "PermissionId");

                            b1.ToTable("RolePermissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoleId");
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("DomainPlayground.Core.Domain.Authorization.UserAccesses.UserAccess", b =>
                {
                    b.OwnsMany("DomainPlayground.Core.Domain.Authorization.UserAccesses.ValueObjects.UserPermissionOverride", "Overrides", b1 =>
                        {
                            b1.Property<Guid>("UserAccessId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("PermissionId")
                                .HasColumnType("int");

                            b1.Property<int>("Effect")
                                .HasColumnType("int");

                            b1.HasKey("UserAccessId", "PermissionId");

                            b1.ToTable("UserAccessOverrides", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserAccessId");
                        });

                    b.OwnsMany("DomainPlayground.Core.Domain.Authorization.UserAccesses.ValueObjects.UserRole", "Roles", b1 =>
                        {
                            b1.Property<Guid>("UserAccessId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("RoleId")
                                .HasColumnType("int");

                            b1.HasKey("UserAccessId", "RoleId");

                            b1.ToTable("UserAccessRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserAccessId");
                        });

                    b.Navigation("Overrides");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
