<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ea8dd5aa-461e-4845-8dca-da0c2b23c3a1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\DomainPlayground.Core.Application\DomainPlayground.Core.Application.csproj" />
    <ProjectReference Include="..\..\Core\DomainPlayground.Core.Domain\DomainPlayground.Core.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\DomainPlayground.Infrastructure.Identity\DomainPlayground.Infrastructure.Identity.csproj" />
    <ProjectReference Include="..\..\Infrastructure\DomainPlayground.Infrastructure.Persistence.Command\DomainPlayground.Infrastructure.Persistence.Commands.csproj" />
    <ProjectReference Include="..\..\Infrastructure\DomainPlayground.Infrastructure.Persistence.Queries\DomainPlayground.Infrastructure.Persistence.Queries.csproj" />
    <ProjectReference Include="..\..\Infrastructure\DomainPlayground.Infrastructure\DomainPlayground.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\DomainPlayground.SharedKernel\DomainPlayground.SharedKernel.csproj" />
  </ItemGroup>

</Project>
