<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
		<PackageReference Include="xunit" Version="2.*" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.*" />
		<PackageReference Include="FluentAssertions" Version="6.*" />
		<PackageReference Include="Moq" Version="4.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Core\DomainPlayground.Core.Application\DomainPlayground.Core.Application.csproj" />
		<ProjectReference Include="..\..\src\Core\DomainPlayground.Core.Domain\DomainPlayground.Core.Domain.csproj" />
		<ProjectReference Include="..\..\src\Shared\DomainPlayground.SharedKernel\DomainPlayground.SharedKernel.csproj" />
	</ItemGroup>

</Project>